# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Charles/Desktop/MIT/Fall 2019/6_111/FPGA SDR Final Project/FPGA_SDR/FPGA_SDR/FPGA_SDR_project/FPGA_SDR_project.srcs/sources_1/ip/AM_FIR_Coeff/AM_FIR_Coeff.xci
# IP: The module: 'AM_FIR_Coeff' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Charles/Desktop/MIT/Fall 2019/6_111/FPGA SDR Final Project/FPGA_SDR/FPGA_SDR/FPGA_SDR_project/FPGA_SDR_project.srcs/sources_1/ip/AM_FIR_Coeff/AM_FIR_Coeff_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AM_FIR_Coeff'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Charles/Desktop/MIT/Fall 2019/6_111/FPGA SDR Final Project/FPGA_SDR/FPGA_SDR/FPGA_SDR_project/FPGA_SDR_project.srcs/sources_1/ip/AM_FIR_Coeff/AM_FIR_Coeff.xci
# IP: The module: 'AM_FIR_Coeff' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Charles/Desktop/MIT/Fall 2019/6_111/FPGA SDR Final Project/FPGA_SDR/FPGA_SDR/FPGA_SDR_project/FPGA_SDR_project.srcs/sources_1/ip/AM_FIR_Coeff/AM_FIR_Coeff_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AM_FIR_Coeff'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
