#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Nov 26 18:12:34 EST 2019
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim AM_BP_Filter_tb_behav -key {Behavioral:sim_1:Functional:AM_BP_Filter_tb} -tclbatch AM_BP_Filter_tb.tcl -log simulate.log"
xsim AM_BP_Filter_tb_behav -key {Behavioral:sim_1:Functional:AM_BP_Filter_tb} -tclbatch AM_BP_Filter_tb.tcl -log simulate.log

